# Generated by Django 2.2.1 on 2019-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190715_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultOmok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('x', models.CharField(max_length=10)),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='stone',
            name='x2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stone',
            name='y2',
            field=models.IntegerField(blank=True),
        ),
    ]
