# Generated by Django 2.2.1 on 2019-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190715_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
