# Generated by Django 2.2.1 on 2019-07-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_session_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultomok',
            name='room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
