# Generated by Django 2.2.1 on 2019-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resultomok_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='color',
            field=models.CharField(blank=True, default='white', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='x2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='y2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
