# Generated by Django 2.2.1 on 2019-07-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190722_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
