# Generated by Django 2.2.1 on 2019-07-31 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blackSession',
            fields=[
                ('colorid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('session_name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultOmok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('x', models.CharField(max_length=10, null=True)),
                ('y', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('blackid', models.CharField(max_length=10, unique=True)),
                ('whiteid', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='whiteSession',
            fields=[
                ('colorid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('session_name', models.CharField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='White',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=10)),
                ('s2', models.CharField(max_length=10)),
                ('get_time', models.DateTimeField(null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_room', to='api.whiteSession')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=50)),
                ('player2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player1_color', models.CharField(default='', max_length=10)),
                ('player2_color', models.CharField(blank=True, max_length=10, null=True)),
                ('player1_status', models.BooleanField(default=False)),
                ('player2_status', models.BooleanField(default=False)),
                ('player_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_session', to='api.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Black',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=10)),
                ('s2', models.CharField(blank=True, max_length=10, null=True)),
                ('get_time', models.DateTimeField(null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_room', to='api.blackSession')),
            ],
        ),
    ]
