# Generated by Django 2.2.3 on 2019-11-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacksession',
            name='timer',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='whitesession',
            name='timer',
            field=models.IntegerField(default=15),
        ),
    ]
