# Generated by Django 2.2.1 on 2019-07-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player2_status',
            field=models.BooleanField(default=False),
        ),
    ]
