# Generated by Django 2.2.1 on 2019-08-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultomok',
            name='turn',
            field=models.IntegerField(null=True),
        ),
    ]
