# Generated by Django 2.2.3 on 2019-07-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='color',
        ),
        migrations.RemoveField(
            model_name='session',
            name='manager_id',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=50)),
                ('player2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player1_color', models.CharField(default='', max_length=10)),
                ('player2_color', models.CharField(blank=True, max_length=10, null=True)),
                ('player_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_session', to='api.Session')),
            ],
        ),
    ]
