# Generated by Django 2.2.1 on 2019-07-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultomok',
            name='room',
            field=models.CharField(max_length=10),
        ),
    ]
