# Generated by Django 2.2.1 on 2019-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190715_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=200),
        ),
    ]
