# Generated by Django 2.2.1 on 2019-07-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190722_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultomok',
            name='x',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultomok',
            name='y',
            field=models.IntegerField(null=True),
        ),
    ]
